const TestnumbersCount = {
  "abstract-reasoning": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "adaptability-and-flexibility": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "advanced-data-structures": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  algebra: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
  },
  arrays: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  average: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "communication-skills": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "comparison-of-quantities": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "conflict-resolution": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "crisis-management": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  css: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
  },
  "data-interpretation": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "data-sufficiency": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "decision-making": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "emotional-intelligence": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "ethical-dilemmas": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  graphs: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "handling-workplace-pressure": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  hashing: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  heaps: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  html: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
  },
  interest: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  javascript: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
    ],
  },
  "leadership-and-teamwork": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "linked-lists": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "logical-reasoning": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "mechanical-reasoning": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
  },
  mensuration: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "mixture-allegation": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  nodejs: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
  },
  "number-series": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
  },
  "numerical-reasoning": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
    ],
  },
  percentage: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "permutation-combination-probability": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "problem-solving-scenarios": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "profit-loss": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  python: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
  },
  queues: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "ratio-proportion": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  reactjs: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
      { value: "test8", label: "Test 8" },
      { value: "test9", label: "Test 9" },
      { value: "test10", label: "Test 10" },
    ],
  },
  simplification: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
      { value: "test6", label: "Test 6" },
      { value: "test7", label: "Test 7" },
    ],
  },
  "situational-judgement": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  "speed-time-distance": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  stacks: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "time-and-work": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "time-management": {
    beginner: [{ value: "test1", label: "Test 1" }],
    intermediate: [{ value: "test1", label: "Test 1" }],
    advanced: [{ value: "test1", label: "Test 1" }],
  },
  trees: {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
      { value: "test5", label: "Test 5" },
    ],
  },
  "verbal-reasoning": {
    beginner: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
      { value: "test4", label: "Test 4" },
    ],
    intermediate: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
    advanced: [
      { value: "test1", label: "Test 1" },
      { value: "test2", label: "Test 2" },
      { value: "test3", label: "Test 3" },
    ],
  },
};

module.exports = TestnumbersCount;
